# Generated by Django 3.0.8 on 2020-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200727_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='values',
            name='genre',
        ),
        migrations.AddField(
            model_name='values',
            name='Humidity',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='values',
            name='Pressure',
            field=models.IntegerField(default=170),
        ),
        migrations.AddField(
            model_name='values',
            name='Temperature',
            field=models.IntegerField(default=170),
        ),
    ]
