# Generated by Django 3.0.8 on 2020-07-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_values_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='Humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='values',
            name='Pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='values',
            name='SMS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='values',
            name='Temperature',
            field=models.IntegerField(default=0),
        ),
    ]
