# Generated by Django 3.0.8 on 2020-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20200728_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='Date_Time',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
